name: .NET Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependências
      run: dotnet restore

    - name: Build da solução
      run: dotnet build --configuration Release --no-restore

    - name: Rodar Testes
      run: dotnet test tests/GestaoPedidos.Tests/GestaoPedidos.Tests.csproj --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"